// Auth
export const LOGIN_USER_SUCCEEDED = 'LOGIN_USER_SUCCEEDED';
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const SIGNUP_USER_SUCCEEDED = 'SIGNUP_USER_SUCCEEDED';
export const SIGNUP_USER_REQUESTED = 'SIGNUP_USER_REQUESTED';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Polls
export const FETCH_POLLS_SUCCEEDED = 'FETCH_POLLS_SUCCEEDED';
export const FETCH_POLLS_REQUESTED = 'FETCH_POLLS_REQUESTED';
export const FETCH_POLLS_FAILED = 'FETCH_POLLS_FAILED';

export const SAVE_USER_POLL_SUCCEEDED = 'SAVE_USER_POLL_SUCCEEDED';
export const SAVE_USER_POLL_REQUESTED = 'SAVE_USER_POLL_REQUESTED';
export const SAVE_USER_POLL_FAILED = 'SAVE_USER_POLL_FAILED';

export const EDIT_USER_POLL_REQUESTED = 'EDIT_USER_POLL_REQUESTED';
export const EDIT_USER_POLL_SUCCEEDED = 'EDIT_USER_POLL_SUCCEEDED';
export const EDIT_USER_POLL_FAILED = 'EDIT_USER_POLL_FAILED';

export const DELETE_USER_POLL_SUCCEEDED = 'DELETE_USER_POLL_SUCCEEDED';
export const DELETE_USER_POLL_FAILED = 'DELETE_USER_POLL_FAILED';
export const DELETE_USER_POLL_REQUESTED = 'DELETE_USER_POLL_REQUESTED';